### ISSUE TITLE
Add solutions on other languages as well

### ISSUE THREAD

**Issue by Saif64** [tanishqj-19/30-Days-of-Leetcode#1]
You should also add the leetcode solutions that that are done on other languages like JS and JAVA in your codebase. I have done Javascript an Java solutions in my [repository](https://github.com/Saif64/Interview-prep) If you want I can add mine or you can contribute/Merge your solutions into mine. If you want we can work together so that the open source contribution can be done.. This is a total win-win situtaion.

**Comment by tanishqj-19** [comment]
Yeah Sure . I would love if you can contribute JS codes for questions and Completing this Challenge!

**Comment by Saif64** [comment]
@tanishqj-19 created a Pull Request Merge and close the issue brother..
